# Generated by Django 4.1.7 on 2026-02-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('water', 'Drink Water'), ('break', 'Take a Break'), ('walk', 'Take a Walk'), ('screen', 'Look Away from Screen')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('default_interval', models.IntegerField(help_text='Default interval in minutes')),
                ('icon', models.CharField(default='🔔', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(help_text='Interval in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.remindertype')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.remindertype')),
            ],
            options={
                'ordering': ['-shown_at'],
            },
        ),
    ]
